export enum ESocketEvent {
    SEND_GROUP_REQUEST = 'SEND_GROUP_REQUEST',
    ACCEPT_GROUP_REQUEST = 'ACCEPT_GROUP_REQUEST',

    INVITE_TO_GROUP = 'INVITE_TO_GROUP',

    SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE',

    UPDATE_ROOM = "UPDATE_ROOM",
}